smurf_symfony_core_system_security_route:
    resource: "@SmurfSymfony2AppBundle/Controller"
    type: annotation
    prefix: /core
    defaults:  { _controller: "SmurfSymfony2AppBundle:Default:index" }