parameters:
#    smurf_app.example.class: Smurf\Symfony2AppBundle\Example

services:
#    smurf_app.example:
#        class: %smurf_app.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
