parameters:
     smurf.symfony2app.dynamicRouter.listener.class:  Smurf\Symfony2AppBundle\EventListener\Symfony2AppDynamicRouterListener

services:
    smurf.symfony2app.dynamicRouter.listener:
        class: %smurf.symfony2app.dynamicRouter.listener.class%
        tags:
            - { name: kernel.event_listener, event: kernel.request, priority: 33 }
            